_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
epochs:
    value: 100
focal_loss_alpha:
    value: 0.7
learning_rate:
    value: 0.001
